package ITI.Messenger;


import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jdesktop.xswingx.PromptSupport;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainPage.java
 *
 * Created on Jan 18, 2015, 3:42:45 AM
 */

/**
 *
 * @author dina
 */
public class MainPage extends javax.swing.JFrame {

    /** Creates new form MainPage */
    public MainPage() {
//Swing.defaultlaf=com.jtattoo.plaf.mcwin.McWinLookAndFeel ;
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
           // UIManager.setLookAndFeel("napkin.NapkinLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        State.setRenderer(new MyRendrer());
        Image FriendImg = Toolkit.getDefaultToolkit().getImage("Friends.png").getScaledInstance(40,40,Image.SCALE_SMOOTH);
        ImageIcon FriendIcon = new ImageIcon(FriendImg) ;
        AddFriendL.setIcon(FriendIcon);
        Image UsrImg = Toolkit.getDefaultToolkit().getImage("FriendIcon.png").getScaledInstance(40,40,Image.SCALE_SMOOTH);
        ImageIcon UsrIcon = new ImageIcon(UsrImg) ;
        UserImageL.setIcon(UsrIcon);
        PromptSupport.setPrompt("search for friends", SearchFT);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InformationPanel = new javax.swing.JPanel();
        State = new javax.swing.JComboBox();
        UserImageL = new javax.swing.JLabel();
        UserNameL = new javax.swing.JLabel();
        ContactProfileChooser = new javax.swing.JTabbedPane();
        FriendsP = new javax.swing.JPanel();
        SearchP = new javax.swing.JPanel();
        AddFriendL = new javax.swing.JLabel();
        SearchFT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        FriendL = new javax.swing.JList();
        ProfileP = new javax.swing.JPanel();
        FirstNameL = new javax.swing.JLabel();
        LastNameL = new javax.swing.JLabel();
        EmailL = new javax.swing.JLabel();
        BirtDateL = new javax.swing.JLabel();
        GenderL = new javax.swing.JLabel();
        CodeL = new javax.swing.JLabel();
        NumberL = new javax.swing.JLabel();
        EditProfileB = new javax.swing.JButton();
        ToolBar = new javax.swing.JMenuBar();
        MsgM = new javax.swing.JMenu();
        ContactM = new javax.swing.JMenu();
        ActionM = new javax.swing.JMenu();
        HelpM = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        InformationPanel.setBackground(new java.awt.Color(153, 0, 153));
        InformationPanel.setLayout(new java.awt.BorderLayout(20, 0));

        State.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Available", "Busy", "Offline", "Invisible" }));
        State.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateActionPerformed(evt);
            }
        });
        InformationPanel.add(State, java.awt.BorderLayout.EAST);
        InformationPanel.add(UserImageL, java.awt.BorderLayout.LINE_START);

        UserNameL.setText("dina abdelbadea");
        InformationPanel.add(UserNameL, java.awt.BorderLayout.CENTER);

        getContentPane().add(InformationPanel, "card2");

        ContactProfileChooser.setBackground(new java.awt.Color(102, 0, 102));

        SearchP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchP.setMaximumSize(new java.awt.Dimension(250, 250));
        SearchP.setMinimumSize(new java.awt.Dimension(30, 30));
        SearchP.setLayout(new java.awt.BorderLayout());

        AddFriendL.setMaximumSize(new java.awt.Dimension(40, 40));
        AddFriendL.setMinimumSize(new java.awt.Dimension(1, 1));
        AddFriendL.setPreferredSize(new java.awt.Dimension(40, 40));
        SearchP.add(AddFriendL, java.awt.BorderLayout.WEST);

        SearchFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SearchFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFTActionPerformed(evt);
            }
        });
        SearchP.add(SearchFT, java.awt.BorderLayout.CENTER);

        FriendL.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(FriendL);

        javax.swing.GroupLayout FriendsPLayout = new javax.swing.GroupLayout(FriendsP);
        FriendsP.setLayout(FriendsPLayout);
        FriendsPLayout.setHorizontalGroup(
            FriendsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SearchP, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );
        FriendsPLayout.setVerticalGroup(
            FriendsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FriendsPLayout.createSequentialGroup()
                .addComponent(SearchP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
        );

        ContactProfileChooser.addTab("Friends", FriendsP);

        ProfileP.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));

        FirstNameL.setText("First name");
        FirstNameL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 0, 102)));

        LastNameL.setText("Last name");
        LastNameL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 0, 102)));

        EmailL.setText("Email");
        EmailL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 0, 102)));

        BirtDateL.setText("Birth day");
        BirtDateL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Birth date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 0, 102)));

        GenderL.setText("Gender");
        GenderL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 0, 102)));

        CodeL.setText("Code");
        CodeL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 0, 102)));

        NumberL.setText("Country");
        NumberL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 0, 102)));

        EditProfileB.setForeground(new java.awt.Color(102, 0, 102));
        EditProfileB.setText("Edit");
        EditProfileB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditProfileB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfilePLayout = new javax.swing.GroupLayout(ProfileP);
        ProfileP.setLayout(ProfilePLayout);
        ProfilePLayout.setHorizontalGroup(
            ProfilePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfilePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfilePLayout.createSequentialGroup()
                        .addGroup(ProfilePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GenderL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(BirtDateL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(LastNameL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(FirstNameL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProfilePLayout.createSequentialGroup()
                                .addComponent(CodeL, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NumberL, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EmailL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilePLayout.createSequentialGroup()
                        .addComponent(EditProfileB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        ProfilePLayout.setVerticalGroup(
            ProfilePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FirstNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailL, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BirtDateL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenderL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfilePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodeL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditProfileB)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        ContactProfileChooser.addTab("Profile", ProfileP);

        getContentPane().add(ContactProfileChooser, "card3");
        ContactProfileChooser.getAccessibleContext().setAccessibleName("Friends");

        MsgM.setText("Messenger");
        ToolBar.add(MsgM);

        ContactM.setText("Contacts");
        ToolBar.add(ContactM);

        ActionM.setText("Action");
        ToolBar.add(ActionM);

        HelpM.setText("Help");
        ToolBar.add(HelpM);

        setJMenuBar(ToolBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StateActionPerformed

    private void SearchFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchFTActionPerformed

    private void EditProfileBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProfileBActionPerformed

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ActionM;
    private javax.swing.JLabel AddFriendL;
    private javax.swing.JLabel BirtDateL;
    private javax.swing.JLabel CodeL;
    private javax.swing.JMenu ContactM;
    private javax.swing.JTabbedPane ContactProfileChooser;
    private javax.swing.JButton EditProfileB;
    private javax.swing.JLabel EmailL;
    private javax.swing.JLabel FirstNameL;
    private javax.swing.JList FriendL;
    private javax.swing.JPanel FriendsP;
    private javax.swing.JLabel GenderL;
    private javax.swing.JMenu HelpM;
    private javax.swing.JPanel InformationPanel;
    private javax.swing.JLabel LastNameL;
    private javax.swing.JMenu MsgM;
    private javax.swing.JLabel NumberL;
    private javax.swing.JPanel ProfileP;
    private javax.swing.JTextField SearchFT;
    private javax.swing.JPanel SearchP;
    private javax.swing.JComboBox State;
    private javax.swing.JMenuBar ToolBar;
    private javax.swing.JLabel UserImageL;
    private javax.swing.JLabel UserNameL;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}

class MyRendrer implements ListCellRenderer
{

    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        JLabel label = new JLabel();
        label.setOpaque(true);
        
        label.setText(value.toString());

        Image AvImg = Toolkit.getDefaultToolkit().getImage("online.png").getScaledInstance(10,10,Image.SCALE_SMOOTH);

        ImageIcon AvIcon = new ImageIcon(AvImg) ;

        Image BusyImg = Toolkit.getDefaultToolkit().getImage("busy.png").getScaledInstance(10,10,Image.SCALE_SMOOTH);

         ImageIcon BusyIcon = new ImageIcon(BusyImg) ;

         Image OffImg = Toolkit.getDefaultToolkit().getImage("offline.png").getScaledInstance(10,10,Image.SCALE_SMOOTH);

         ImageIcon OffIcon = new ImageIcon(OffImg) ;

         Image InvImg = Toolkit.getDefaultToolkit().getImage("idle.png").getScaledInstance(10,10,Image.SCALE_SMOOTH);

         ImageIcon InvIcon = new ImageIcon(InvImg) ;

        if (value.equals("Available"))
            label.setIcon(AvIcon);
        else if(value.equals("Busy"))
            label.setIcon(BusyIcon);
         else if(value.equals("Offline"))
            label.setIcon(OffIcon);
        else label.setIcon(InvIcon);

         if (isSelected)
            label.setBackground(Color.gray);
        

        return label;
    }
}


