/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainMPage.java
 *
 * Created on Jan 20, 2015, 6:08:40 AM
 */
package ITI.Messenger;


import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jdesktop.xswingx.PromptSupport;
import de.javasoft.plaf.synthetica.SyntheticaStandardLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaSkyMetallicLookAndFeel;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;


/**
 *
 * @author dina
 */
public class MainMPage extends javax.swing.JFrame {

    /** Creates new form MainMPage */
    public MainMPage() {
        initComponents();
        try {
            UIManager.setLookAndFeel(new SyntheticaSkyMetallicLookAndFeel());
        } catch (Exception e) {
            e.printStackTrace();
        }
        SwingUtilities.updateComponentTreeUI(this);

        Image FriendImg = Toolkit.getDefaultToolkit().getImage("fRIENDS.png").getScaledInstance(40, 40, Image.SCALE_SMOOTH);

        ImageIcon FriendIcon = new ImageIcon(FriendImg);
        AddFriendL.setIcon(FriendIcon);

        Image userImg = Toolkit.getDefaultToolkit().getImage("friendIcon.png").getScaledInstance(60, 60, Image.SCALE_SMOOTH);

        ImageIcon userIcon = new ImageIcon(userImg);
        UserImageL.setIcon(userIcon);

        StateC.setRenderer(new MyRendrer());
    }

    public JLabel getBirtDateL() {
        return BirtDateL;
    }

    public void setBirtDateL(JLabel BirtDateL) {
        this.BirtDateL = BirtDateL;
    }

    public JLabel getEmailL() {
        return EmailL;
    }

    public void setEmailL(JLabel EmailL) {
        this.EmailL = EmailL;
    }

    public JLabel getFirstNameL() {
        return FirstNameL;
    }

    public void setFirstNameL(JLabel FirstNameL) {
        this.FirstNameL = FirstNameL;
    }

    public JLabel getGenderL() {
        return GenderL;
    }

    public void setGenderL(JLabel GenderL) {
        this.GenderL = GenderL;
    }

    public JLabel getLastNameL() {
        return LastNameL;
    }

    public void setLastNameL(JLabel LastNameL) {
        this.LastNameL = LastNameL;
    }

    public JLabel getNumberL() {
        return NumberL;
    }

   

    public void setNumberL(JLabel NumberL) {
        this.NumberL = NumberL;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataP =  new NewJPanel("MainBackgnd.jpg");
        InformationP =  new NewJPanel("MainBackgnd.jpg");
        UserImageL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        StateC = new javax.swing.JComboBox();
        FileChooserP =  new NewJPanel("MainBackgnd.jpg");
        ContactProfileChooser = new javax.swing.JTabbedPane();
        FriendsP =  new NewJPanel("MainBackgnd.jpg");
        SearchP = new javax.swing.JPanel();
        AddFriendL = new javax.swing.JLabel();
        SearchFriendL = new javax.swing.JTextField();
        FriendSP = new javax.swing.JScrollPane();
        FriendL = new javax.swing.JList();
        Profile = new javax.swing.JPanel();
        FirstNameL = new javax.swing.JLabel();
        LastNameL = new javax.swing.JLabel();
        EmailL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BirtDateL = new javax.swing.JLabel();
        GenderL = new javax.swing.JLabel();
        NumberL = new javax.swing.JLabel();
        EditProfileB = new javax.swing.JButton();
        MenuM = new javax.swing.JMenuBar();
        MessengerM = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        ContactsM = new javax.swing.JMenu();
        ActionM = new javax.swing.JMenu();
        HelpM = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Gisha", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Team");

        StateC.setFont(new java.awt.Font("Gisha", 0, 11)); // NOI18N
        StateC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Available", "Busy", "Offline", "Invisible" }));
        StateC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InformationPLayout = new javax.swing.GroupLayout(InformationP);
        InformationP.setLayout(InformationPLayout);
        InformationPLayout.setHorizontalGroup(
            InformationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformationPLayout.createSequentialGroup()
                .addComponent(UserImageL, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InformationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StateC, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        InformationPLayout.setVerticalGroup(
            InformationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserImageL, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InformationPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StateC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(InformationPLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        ContactProfileChooser.setBackground(new java.awt.Color(102, 0, 102));
        ContactProfileChooser.setFont(new java.awt.Font("Gisha", 1, 14)); // NOI18N
        ContactProfileChooser.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                ContactProfileChooserComponentRemoved(evt);
            }
        });
        ContactProfileChooser.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ContactProfileChooserStateChanged(evt);
            }
        });

        SearchP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchP.setMaximumSize(new java.awt.Dimension(250, 250));
        SearchP.setMinimumSize(new java.awt.Dimension(30, 30));
        SearchP.setLayout(new java.awt.BorderLayout());

        AddFriendL.setMaximumSize(new java.awt.Dimension(40, 40));
        AddFriendL.setMinimumSize(new java.awt.Dimension(1, 1));
        AddFriendL.setPreferredSize(new java.awt.Dimension(40, 40));
        SearchP.add(AddFriendL, java.awt.BorderLayout.WEST);

        SearchFriendL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SearchFriendL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFriendLActionPerformed(evt);
            }
        });
        SearchP.add(SearchFriendL, java.awt.BorderLayout.CENTER);

        FriendL.setFont(new java.awt.Font("Gisha", 1, 14)); // NOI18N
        FriendL.setForeground(new java.awt.Color(102, 0, 102));
        FriendL.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Christina - Today is sunny horaaay !!", "Mohamed - ITI", "ITI", "ITI everywhere ..", "Sara - if you believe you can", "you can", "Yasser - :P", "Leila - <3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        FriendL.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        FriendL.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                FriendLValueChanged(evt);
            }
        });
        FriendSP.setViewportView(FriendL);

        javax.swing.GroupLayout FriendsPLayout = new javax.swing.GroupLayout(FriendsP);
        FriendsP.setLayout(FriendsPLayout);
        FriendsPLayout.setHorizontalGroup(
            FriendsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SearchP, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
            .addComponent(FriendSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );
        FriendsPLayout.setVerticalGroup(
            FriendsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FriendsPLayout.createSequentialGroup()
                .addComponent(SearchP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FriendSP, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
        );

        ContactProfileChooser.addTab("Friends", FriendsP);

        Profile.setBackground(new java.awt.Color(255, 255, 255));
        Profile.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));

        FirstNameL.setBackground(new java.awt.Color(240, 117, 240));
        FirstNameL.setFont(new java.awt.Font("Gisha", 1, 14)); // NOI18N
        FirstNameL.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameL.setText("Team");
        FirstNameL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 0, 102))); // NOI18N

        LastNameL.setFont(new java.awt.Font("Gisha", 1, 14)); // NOI18N
        LastNameL.setForeground(new java.awt.Color(255, 255, 255));
        LastNameL.setText("Team");
        LastNameL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 0, 102))); // NOI18N

        EmailL.setFont(new java.awt.Font("Gisha", 1, 14)); // NOI18N
        EmailL.setForeground(new java.awt.Color(255, 255, 255));
        EmailL.setText("Team@team.com");
        EmailL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 0, 102))); // NOI18N

        BirtDateL.setFont(new java.awt.Font("Gisha", 1, 14)); // NOI18N
        BirtDateL.setForeground(new java.awt.Color(255, 255, 255));
        BirtDateL.setText("1 Feb 2015");
        BirtDateL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Birth date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 0, 102))); // NOI18N

        GenderL.setFont(new java.awt.Font("Gisha", 1, 14)); // NOI18N
        GenderL.setForeground(new java.awt.Color(255, 255, 255));
        GenderL.setText("Both");
        GenderL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 0, 102))); // NOI18N

        NumberL.setFont(new java.awt.Font("Gisha", 1, 14)); // NOI18N
        NumberL.setForeground(new java.awt.Color(255, 255, 255));
        NumberL.setText("xxxxxxxx");
        NumberL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 0, 102))); // NOI18N

        EditProfileB.setFont(new java.awt.Font("Gisha", 1, 14)); // NOI18N
        EditProfileB.setText("Edit");
        EditProfileB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditProfileB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayout.createSequentialGroup()
                        .addComponent(EditProfileB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayout.createSequentialGroup()
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NumberL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GenderL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(BirtDateL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(LastNameL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(FirstNameL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProfileLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(EmailL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                        .addGap(71, 71, 71))))
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FirstNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(EmailL, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BirtDateL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenderL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumberL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditProfileB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FirstNameL.getAccessibleContext().setAccessibleDescription("");

        ContactProfileChooser.addTab("Profile", Profile);

        javax.swing.GroupLayout FileChooserPLayout = new javax.swing.GroupLayout(FileChooserP);
        FileChooserP.setLayout(FileChooserPLayout);
        FileChooserPLayout.setHorizontalGroup(
            FileChooserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(FileChooserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FileChooserPLayout.createSequentialGroup()
                    .addComponent(ContactProfileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        FileChooserPLayout.setVerticalGroup(
            FileChooserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
            .addGroup(FileChooserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FileChooserPLayout.createSequentialGroup()
                    .addComponent(ContactProfileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(61, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout DataPLayout = new javax.swing.GroupLayout(DataP);
        DataP.setLayout(DataPLayout);
        DataPLayout.setHorizontalGroup(
            DataPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataPLayout.createSequentialGroup()
                .addComponent(InformationP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(127, 127, 127))
            .addComponent(FileChooserP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DataPLayout.setVerticalGroup(
            DataPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataPLayout.createSequentialGroup()
                .addComponent(InformationP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FileChooserP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MessengerM.setText("Messenger");

        jMenuItem1.setText("Sign Out");
        MessengerM.add(jMenuItem1);

        MenuM.add(MessengerM);

        ContactsM.setText("Contacts");
        MenuM.add(ContactsM);

        ActionM.setText("Action");
        MenuM.add(ActionM);

        HelpM.setText("Help");
        MenuM.add(HelpM);

        setJMenuBar(MenuM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DataP, javax.swing.GroupLayout.PREFERRED_SIZE, 327, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DataP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StateCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateCActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_StateCActionPerformed

    private void SearchFriendLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFriendLActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_SearchFriendLActionPerformed

    private void EditProfileBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileBActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_EditProfileBActionPerformed

    private void FriendLValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_FriendLValueChanged
        // TODO add your handling code here:
        ChatPage chat = new ChatPage();
        this.dispose();
        chat.show();
        System.out.println("kdfsg");
    }//GEN-LAST:event_FriendLValueChanged

    public JTabbedPane getContactProfileChooser() {
        return ContactProfileChooser;
    }

    private void ContactProfileChooserComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_ContactProfileChooserComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactProfileChooserComponentRemoved

    private void ContactProfileChooserStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ContactProfileChooserStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactProfileChooserStateChanged

    // * @param args the command line arguments
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainMPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ActionM;
    private javax.swing.JLabel AddFriendL;
    private javax.swing.JLabel BirtDateL;
    private javax.swing.JTabbedPane ContactProfileChooser;
    private javax.swing.JMenu ContactsM;
    private javax.swing.JPanel DataP;
    private javax.swing.JButton EditProfileB;
    private javax.swing.JLabel EmailL;
    private javax.swing.JPanel FileChooserP;
    private javax.swing.JLabel FirstNameL;
    private javax.swing.JList FriendL;
    private javax.swing.JScrollPane FriendSP;
    private javax.swing.JPanel FriendsP;
    private javax.swing.JLabel GenderL;
    private javax.swing.JMenu HelpM;
    private javax.swing.JPanel InformationP;
    private javax.swing.JLabel LastNameL;
    private javax.swing.JMenuBar MenuM;
    private javax.swing.JMenu MessengerM;
    private javax.swing.JLabel NumberL;
    private javax.swing.JPanel Profile;
    private javax.swing.JTextField SearchFriendL;
    private javax.swing.JPanel SearchP;
    private javax.swing.JComboBox StateC;
    private javax.swing.JLabel UserImageL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
class MyRendrer implements ListCellRenderer {

    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        JLabel label = new JLabel();
        label.setOpaque(true);

        label.setText(value.toString());

        Image AvImg1 = Toolkit.getDefaultToolkit().getImage("online.png").getScaledInstance(10, 10, Image.SCALE_SMOOTH);

        ImageIcon AvIcon1 = new ImageIcon(AvImg1);

        Image BusyImg = Toolkit.getDefaultToolkit().getImage("busy.png").getScaledInstance(10, 10, Image.SCALE_SMOOTH);

        ImageIcon BusyIcon = new ImageIcon(BusyImg);

        Image OffImg = Toolkit.getDefaultToolkit().getImage("offline.png").getScaledInstance(10, 10, Image.SCALE_SMOOTH);

        ImageIcon OffIcon = new ImageIcon(OffImg);

        Image InvImg = Toolkit.getDefaultToolkit().getImage("idle.png").getScaledInstance(10, 10, Image.SCALE_SMOOTH);

        ImageIcon InvIcon = new ImageIcon(InvImg);

        if (value.equals("Available")) {
            label.setIcon(AvIcon1);

        } else if (value.equals("Busy")) {
            label.setIcon(BusyIcon);
        } else if (value.equals("Offline")) {
            label.setIcon(OffIcon);
        } else {
            label.setIcon(InvIcon);
        }

        if (isSelected) {
            label.setBackground(Color.gray);
        }


        return label;
    }
}
