/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MsgAll.java
 *
 * Created on Jan 19, 2015, 12:59:17 AM
 */

package ITI.Messenger;

/**
 *
 * @author dina
 */
public class MsgAll extends javax.swing.JFrame {

    /** Creates new form MsgAll */
    public MsgAll() {
        initComponents();
        this.add(new MainPage());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MsgAll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
