package ITI.Messenger;


import de.javasoft.plaf.synthetica.SyntheticaSkyMetallicLookAndFeel;
import java.awt.Color;
import javax.swing.*;
import org.jdesktop.xswingx.PromptSupport;
import java.awt.Image;
import java.awt.Toolkit;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author engy
 */
public class SignIn extends javax.swing.JFrame {

    ChatPage chat;
    
    MainMPage mainPage;
    //NewJDialog dialog;
    /**
     * Creates new form SignIn
     */
    public SignIn() {
        
        try 
    {
      UIManager.setLookAndFeel(new SyntheticaSkyMetallicLookAndFeel());
    } 
    catch (Exception e) 
    {
      e.printStackTrace();
    }
        
        initComponents();
        //PromptSupport.setPrompt("user email", EmailT);
        //PromptSupport.setPrompt("password", PasswordT);
        InvalidEmailL.setVisible(false);
        InvalidPassL.setVisible(false);
        //Image flower6 = Toolkit.getDefaultToolkit().getImage("flower6.jpg").getScaledInstance(1000,1000,Image.SCALE_SMOOTH);
        ImageIcon iconSignIn = new ImageIcon("MainBackgnd.jpg");
        jLabel1.setIcon(iconSignIn); 
        
        chat = new ChatPage();
        mainPage = new MainMPage();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignInP = new javax.swing.JPanel();
        EmailL = new javax.swing.JLabel();
        EmailT = new javax.swing.JTextField();
        PasswordL = new javax.swing.JLabel();
        PasswordT = new javax.swing.JTextField();
        SignInB = new javax.swing.JButton();
        orL = new javax.swing.JLabel();
        SignUpB = new javax.swing.JButton();
        SmilleyIconL = new javax.swing.JLabel();
        InvalidPassL = new javax.swing.JLabel();
        InvalidEmailL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 700));
        setResizable(false);

        SignInP.setLayout(null);

        EmailL.setFont(new java.awt.Font("Gisha", 1, 14)); // NOI18N
        EmailL.setForeground(new java.awt.Color(255, 255, 255));
        EmailL.setText("Enter email:");
        SignInP.add(EmailL);
        EmailL.setBounds(50, 260, 222, 17);

        EmailT.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        EmailT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailTKeyTyped(evt);
            }
        });
        SignInP.add(EmailT);
        EmailT.setBounds(50, 280, 247, 38);

        PasswordL.setFont(new java.awt.Font("Gisha", 1, 14)); // NOI18N
        PasswordL.setForeground(new java.awt.Color(255, 255, 255));
        PasswordL.setText("Enter password:");
        SignInP.add(PasswordL);
        PasswordL.setBounds(50, 390, 250, 17);
        SignInP.add(PasswordT);
        PasswordT.setBounds(50, 410, 247, 39);

        SignInB.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        SignInB.setText("Sign In");
        SignInB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInBActionPerformed(evt);
            }
        });
        SignInP.add(SignInB);
        SignInB.setBounds(123, 532, 93, 30);

        orL.setFont(new java.awt.Font("Gisha", 1, 14)); // NOI18N
        orL.setForeground(new java.awt.Color(255, 255, 255));
        orL.setText("OR");
        SignInP.add(orL);
        orL.setBounds(160, 570, 40, 30);

        SignUpB.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        SignUpB.setText("Sign Up");
        SignUpB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBActionPerformed(evt);
            }
        });
        SignInP.add(SignUpB);
        SignUpB.setBounds(120, 610, 93, 30);

        SmilleyIconL.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\messenger V2\\messenger V1\\JavaApplication15\\Windows-Messenger-icon.png")); // NOI18N
        SignInP.add(SmilleyIconL);
        SmilleyIconL.setBounds(41, 10, 280, 230);

        InvalidPassL.setForeground(new java.awt.Color(255, 0, 0));
        InvalidPassL.setText("* Invalid");
        SignInP.add(InvalidPassL);
        InvalidPassL.setBounds(120, 460, 159, 20);

        InvalidEmailL.setForeground(new java.awt.Color(255, 0, 0));
        InvalidEmailL.setText("* Invalid");
        SignInP.add(InvalidEmailL);
        InvalidEmailL.setBounds(90, 340, 159, 30);

        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        SignInP.add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 680);

        getContentPane().add(SignInP, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBActionPerformed
        // TODO add your handling code here:
        this.dispose();
        SignUp signup = new SignUp();
        signup.show();
    }//GEN-LAST:event_SignUpBActionPerformed

    private void SignInBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInBActionPerformed
        this.dispose();
       // chat.show();
       mainPage.show();
    }//GEN-LAST:event_SignInBActionPerformed

    private void EmailTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailTKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailL;
    private javax.swing.JTextField EmailT;
    private javax.swing.JLabel InvalidEmailL;
    private javax.swing.JLabel InvalidPassL;
    private javax.swing.JLabel PasswordL;
    private javax.swing.JTextField PasswordT;
    private javax.swing.JButton SignInB;
    private javax.swing.JPanel SignInP;
    private javax.swing.JButton SignUpB;
    private javax.swing.JLabel SmilleyIconL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel orL;
    // End of variables declaration//GEN-END:variables

public String getUserName(){
      return EmailT.getText();
  }
  
  public String getPassword(){
      return PasswordT.getText();
  }
  
  public JButton getSignInButton(){
      return SignInB;
  }
  
  public JButton getSignUpButton(){
      return SignUpB;
  }
  
  public void setUserNameRequiredLabel(boolean b, int mode){
      InvalidEmailL.setVisible(b);
      if(mode==1){//mode 1 for null
          InvalidEmailL.setText("Your User Name Is Required");
      }
      else if(mode==2){//mode 2 for wrong input
          InvalidEmailL.setText("Invalid User name");
      }
  }
  
  public void setPasswordRequiredRequiredLabel(boolean b, int mode){
      InvalidPassL.setVisible(b);
      if(mode==1){//mode 1 for null
          InvalidPassL.setText("Your Password Is Required");
      }
      else if(mode==2){//mode 2 for wrong input
          InvalidPassL.setText("Invalid Password");
      }
  }

}
